<a href="https://colab.research.google.com/github/nithzsenpai/python-/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=False) #using linspace
print(x)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
d=np.arange(start=1,stop=10,step=2) #eqully spaced numbers
print(d)

[1 3 5 7 9]


In [ ]:
d=np.ones((3,4)) # printing the matrix with all ones
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
z=np.zeros((1,3)) #print 1 row 3 columns with all 0s
print(z)


[[0. 0. 0.]]


In [ ]:
u=np.random.rand(5) #random numbers
print(u)

[0.49552722 0.43285357 0.80251952 0.99734976 0.0121743 ]


In [ ]:
u=np.random.rand(4,3) #random numbers
print(u)

[[0.98419629 0.85978882 0.38621485]
 [0.33112463 0.28992296 0.07622306]
 [0.05057889 0.73442128 0.02711002]
 [0.25524633 0.38998918 0.92712149]]


In [ ]:
grid=np.arange(start=1,stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])#axis 0 =column
#axis 1=rowwise
np.sum(A)
np.sum(A,axis=0)
np.sum(A,axis=1)


array([ 6, 15, 24])

In [ ]:
np.sum(A,axis=0)

array([12, 15, 18])

In [ ]:
b=np.arange(start=11,stop=20).reshape(3,3) #add two matrices
np.add(A,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
print(A+b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
np.subtract(A,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np #transpose

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

np.transpose(arr)



array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:

a_col=np.append(A,[[12,54,23]],axis=1)


print(a_col)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a_ins=np.insert(A,1,[13,14,15],axis=0) #array, which row-1,row to add , axis=0 row if one column
print(a_ins)

[[ 1  2  3]
 [13 14 15]
 [ 4  5  6]
 [ 7  8  9]]


## tuples

In [ ]:
tuple1=(2,4,6,3,7)
tuple2=(1,2,3)
print(tuple1+tuple2)

(2, 4, 6, 3, 7, 1, 2, 3)
